trigger:
  branches:
    include:
    - dev
    - release-*
pr:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

jobs:
- job:
  strategy:
    matrix:
      linux_hdfs:
        imageName: 'ubuntu-16.04'
        TILEDB_HDFS: ON
        CXX: g++

  pool:
    vmImage: $(imageName)
  steps:
  - template: scripts/azure-linux_mac.yml

- job: Windows
  strategy:
    matrix:
      VS2017:
        imageName: 'vs2017-win2016'
        TILEDB_S3: OFF
  pool:
    vmImage: $(imageName)
  steps:
  - template: scripts/azure-windows.yml
