trigger:
  branches:
    include:
    - dev
    - release-*
pr:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string

jobs:
- job:
  strategy:
    matrix:
      macOS_gcs:
        imageName: 'macOS-10.14'
        TILEDB_GCS: ON
        TILEDB_STATIC: OFF
        CXX: clang++

  pool:
    vmImage: $(imageName)
  steps:
  - template: scripts/azure-linux_mac.yml

